.docker-common: &docker-common
  image: docker.io/library/docker:27.2.1-cli@sha256:1a7292ebe42a8e32e66daade95487a1726de20ed5253dacdc28b188e7106a83d
  rules:
    - if: $CI_COMMIT_TAG

.mr-common: &mr-common
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

.pnpm-cache: &pnpm-cache
  before_script:
    - pnpm config set store-dir .pnpm
    - pnpm install
  cache:
    paths:
      - .pnpm

default:
  tags:
    - default

docker-image:
  <<: *docker-common
  parallel:
    matrix:
      - ARCH:
          - arm64
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_SHA-$ARCH . -f docker/Dockerfile
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_SHA-$ARCH
  tags:
    - $ARCH

docker-manifest:
  <<: *docker-common
  needs:
    - docker-image
  parallel:
    matrix:
      - TAG:
          - latest
          - $CI_COMMIT_TAG
  script:
    - docker login registry.zrnt.dev -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker manifest rm registry.zrnt.dev/$CI_PROJECT_PATH:$TAG || true
    - docker manifest create registry.zrnt.dev/$CI_PROJECT_PATH:$TAG registry.zrnt.dev/$CI_PROJECT_PATH:$CI_COMMIT_SHA-arm64
    - docker manifest push registry.zrnt.dev/$CI_PROJECT_PATH:$TAG

mr-fmt-prettier:
  <<: *mr-common
  <<: *pnpm-cache
  image: registry.zrnt.dev/oci/prettier:v1.0.7@sha256:a6f214a9ec4e9be58fe8549aa7442adad8cf1d152913468ea9764522ca84b3c2
  script:
    - prettier --check .

mr-lint-docker-compose:
  <<: *mr-common
  image: docker.io/library/docker:27.2.1-cli@sha256:1a7292ebe42a8e32e66daade95487a1726de20ed5253dacdc28b188e7106a83d
  script:
    - find . -name 'docker-compose.yml' | while read f ; do docker compose -f "$f" config -q ; done

mr-lint-dockerfile:
  <<: *mr-common
  image: registry.zrnt.dev/oci/hadolint:v1.0.9@sha256:a003fd0d6bdbbfbb5442f79a786e0d97dcb3d2adae20bdee6195f5ad2b8b47db
  script:
    - find . -name 'Dockerfile' | while read f ; do hadolint "$f" ; done

mr-lint-js:
  <<: *mr-common
  <<: *pnpm-cache
  image: registry.zrnt.dev/oci/base:v1.1.6@sha256:02b09f8c673594faa4634cdaccfb1dcf24790c2c8195d394d6bf4045811a1f32
  script:
    - pnpm run check

mr-lint-markdown:
  <<: *mr-common
  image: registry.zrnt.dev/oci/markdownlint-cli2:v1.0.2@sha256:876d4f030008dcc254e334b186adab9bf8dc2396f5b94e137c65a1e189cd891c
  script:
    - markdownlint-cli2 **/*.md

mr-lint-markdown-pandoc:
  <<: *mr-common
  image: registry.zrnt.dev/oci/pandoc:v1.1.2@sha256:bc394e661b95eb40b74baa828fabcc2936148a106099cf6cb927136ea3bf4e8e
  script:
    - find . -name '*.md' | while read f ; do pandoc --mathjax --to html5 --wrap=none --fail-if-warnings "$f" > /dev/null ; done
    - git diff --quiet

mr-lint-yaml:
  <<: *mr-common
  image: registry.zrnt.dev/oci/yamllint:v1.0.8@sha256:a138f0779b0cba15fefb0f8c73dc69aa3ab454497adddacc9b04c822ba7120e8
  script:
    - yamllint -c .gitlab/yamllint.yml .

semantic-release:
  image: registry.zrnt.dev/oci/semantic-release:v1.0.8@sha256:591fd305ca41b35aa091ff07527e7c6c8a13152721a6007f93e474c4050eb45b
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_AUTHOR != "$COMMITTER_NAME <$COMMITTER_EMAIL>"
  script:
    - git config user.name "$COMMITTER_NAME"
    - git config user.email "$COMMITTER_EMAIL"
    - cp .gitlab/release.json .releaserc
    - semantic-release
  variables:
    COMMITTER_EMAIL: semantic-release-bot@zarantonello.dev
    COMMITTER_NAME: Semantic Release Bot
