.mr-common:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

.pnpm-cache:
  before_script:
    - pnpm config set store-dir .pnpm
    - pnpm install
  cache:
    paths:
      - .pnpm

default:
  tags:
    - default

docker-image:
  image: docker.io/library/docker:27.3.1-cli@sha256:6806d2764925d3b483f9732422b95321781765aeece274b4e60063d02e13efd6
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_SHA-$ARCH . -f docker/Dockerfile
    - |
      for t in "latest" "$CI_COMMIT_TAG"; do
        docker tag $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_SHA-$ARCH $CI_REGISTRY/$CI_PROJECT_PATH:$t
        docker push $CI_REGISTRY/$CI_PROJECT_PATH:$t
      done
  tags:
    - arm64

mr-fmt-prettier:
  extends:
    - .mr-common
    - .pnpm-cache
  image: registry.zrnt.dev/oci/prettier:v1.0.10@sha256:950579d4ab941300ccff5c8e0449bf74c01bbc8df79a34fb9b53f1525dbdc026
  script: prettier --check .

mr-lint-docker-compose:
  extends: .mr-common
  image: docker.io/library/docker:27.3.1-cli@sha256:6806d2764925d3b483f9732422b95321781765aeece274b4e60063d02e13efd6
  script: find . -name 'docker-compose.yml' | while read f ; do docker compose -f "$f" config -q ; done

mr-lint-dockerfile:
  extends: .mr-common
  image: registry.zrnt.dev/oci/hadolint:v1.0.12@sha256:787b3b1f3ec16ce96ea96264ef25d0519ccd3983e7029162bf4575cc741ef74f
  script: find . -name 'Dockerfile' | while read f ; do hadolint "$f" ; done

mr-lint-js:
  extends:
    - .mr-common
    - .pnpm-cache
  image: registry.zrnt.dev/oci/base:v1.1.9@sha256:56273b54431b31471aa67acdaa6d7c6a987c031e516e6928baa9cdfeea1b5f8d
  script:
    - pnpm run check
    - pnpm run build

mr-lint-markdown:
  extends: .mr-common
  image: registry.zrnt.dev/oci/markdownlint-cli2:v1.0.5@sha256:8687f662026c3ac3171a0bfcfb2b749b0d9881de79205e5afcada5a63de2668c
  script: markdownlint-cli2 --config .gitlab/config.markdownlint.json *.md *.mdx

mr-lint-yaml:
  extends: .mr-common
  image: registry.zrnt.dev/oci/yamllint:v1.0.11@sha256:c90581e1770d20c9a2c7a138b06c0c0204764bf9695afe381c19728e2b1c0080
  script: yamllint -c .gitlab/yamllint.yml .

semantic-release:
  image: registry.zrnt.dev/oci/semantic-release:v1.0.11@sha256:a08784fadcdf89d3394b1bf519bd69fba950f4645189b38d1e50ec5992104124
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - git config user.name "Semantic Release Bot"
    - git config user.email 'semantic-release-bot@zarantonello.dev'
    - cp .gitlab/release.json .releaserc
    - semantic-release
