CSS_STYLELINT_FILE_EXTENSIONS:
  - .astro
  - .css
DISABLE:
  - SPELL
DISABLE_LINTERS:
  - REPOSITORY_DEVSKIM
JAVASCRIPT_DEFAULT_STYLE: prettier
MARKDOWN_MARKDOWNLINT_FILE_EXTENSIONS:
  - .md
  - .mdx
TYPESCRIPT_DEFAULT_STYLE: prettier
