DISABLE:
  - SPELL
DISABLE_LINTERS:
  - TYPESCRIPT_STANDARD
  - JAVASCRIPT_STANDARD
  - MARKDOWN_MARKDOWN_LINK_CHECK
GITHUB_COMMENT_REPORTER: false
GITHUB_STATUS_REPORTER: true
JAVASCRIPT_DEFAULT_STYLE: prettier
MARKDOWN_MARKDOWNLINT_FILE_EXTENSIONS:
  - .md
  - .mdx
TYPESCRIPT_DEFAULT_STYLE: prettier
