FROM docker.io/library/node:23.0.0-bookworm@sha256:9d09fa506f5b8465c5221cbd6f980e29ae0ce9a3119e2b9bc0842e6a3f37bb59

RUN corepack enable

ENTRYPOINT []

RUN userdel node
USER vscode

HEALTHCHECK NONE
