# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - commands:
      - pip install --root-user-action=ignore --cache-dir=/cache/pip --progress-bar=off "commitizen==$COMMITIZEN_VERSION"
      - cz check --message "$CI_COMMIT_MESSAGE"
    environment:
      # renovate: datasource=pypi depName=commitizen versioning=pep440
      COMMITIZEN_VERSION: 3.30.0
    image: docker.io/library/python:3.13.0-alpine@sha256:feee4734fdc44cc09a3c9cdb72e05bb8ff7e964f64766bc1a68638b2c667cf35
    name: check-commitizen
    volumes:
      - wp-cache_global_pip:/cache/pip

when:
  - event: pull_request
