# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - commands:
      - corepack enable
      - pnpm config --global set store-dir /cache/pnpm
      - pnpm install
      - pnpm check:stylelint
    image: docker.io/library/node:23.0.0-bookworm@sha256:9d09fa506f5b8465c5221cbd6f980e29ae0ce9a3119e2b9bc0842e6a3f37bb59
    name: check-stylelint
    volumes:
      - wp-cache_${CI_REPO_REMOTE_ID}_pnpm:/cache/pnpm

when:
  - event: pull_request
