# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - commands:
      - apt update
      - apt install --no-install-recommends -y git
      - bun install
      - bun run build
    image: docker.io/oven/bun:1.1.33-slim@sha256:fac38fc9f43345a8dea1f354c3e8976f0a7610050049d12d72bab335ea4905e6
    name: check-build
    volumes:
      - wp-cache_global_bun:/root/.bun/install/cache/

when:
  - event: pull_request
