# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - commands:
      # Setup pnpm
      - corepack enable
      - pnpm config --global set store-dir /cache/pnpm

      - pnpm install
      - pnpm exec playwright install chromium --with-deps
      - pnpm build
    environment:
      DEBIAN_FRONTEND: noninteractive
    image: docker.io/library/node:23.0.0-bookworm@sha256:9d09fa506f5b8465c5221cbd6f980e29ae0ce9a3119e2b9bc0842e6a3f37bb59
    name: check-build
    volumes:
      - wp-cache_${CI_REPO_REMOTE_ID}_playwright:/root/.cache/ms-playwright
      - wp-cache_${CI_REPO_REMOTE_ID}_pnpm:/cache/pnpm
      - wp-cache_global_apt-cache:/var/cache/apt
      - wp-cache_global_apt-lists:/var/lib/apt/lists

when:
  - event: pull_request
