# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - commands:
      - corepack enable
      - pnpm config set store-dir /pnpm
      - pnpm install
      - pnpm check:stylelint
    image: docker.io/library/node:22.9.0-bookworm@sha256:f2f00f9d041d78b2a76ce80894602a5260ccada74ac294eeb07925a51707d564
    name: check-stylelint
    volumes:
      - woodpecker-repo-${CI_REPO_REMOTE_ID}-pnpm:/pnpm

when:
  - event: pull_request
