# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - commands:
      # Setup pnpm
      - corepack enable
      - pnpm config --global set store-dir /cache/pnpm

      - pnpm install
      - pnpm exec playwright install chromium --with-deps
      - pnpm build
    image: docker.io/library/node:23.0.0-bookworm@sha256:e96bb23d6ba66e6e2913f72207de972e3f36ee5c5ce77966016192e59277a73a
    name: check-build
    volumes:
      - wp-cache_${CI_REPO_REMOTE_ID}_playwright:/root/.cache/ms-playwright
      - wp-cache_${CI_REPO_REMOTE_ID}_pnpm:/cache/pnpm
      - wp-cache_global_apt-cache:/var/cache/apt
      - wp-cache_global_apt-lists:/var/lib/apt/lists

when:
  - event: pull_request
