# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - commands:
      # Setup pnpm
      - corepack enable
      - pnpm config --global set store-dir /cache/pnpm

      - pnpm install
      - pnpm exec playwright install chromium --with-deps
      - pnpm build
    image: docker.io/library/node:23.0.0-bookworm@sha256:e643c0b70dca9704dff42e12b17f5b719dbe4f95e6392fc2dfa0c5f02ea8044d
    name: check-build
    volumes:
      - wp-cache_${CI_REPO_REMOTE_ID}_playwright:/root/.cache/ms-playwright
      - wp-cache_${CI_REPO_REMOTE_ID}_pnpm:/cache/pnpm
      - wp-cache_global_apt-cache:/var/cache/apt
      - wp-cache_global_apt-lists:/var/lib/apt/lists

when:
  - event: pull_request
