# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - commands:
      - deno run --allow-read --allow-sys --allow-env --node-modules-dir=none "npm:markdownlint-cli2@$MARKDOWNLINT_CLI2_VERSION" **/*.md **/*.mdx
    environment:
      # renovate: datasource=npm depName=markdownlint-cli2 versioning=npm
      MARKDOWNLINT_CLI2_VERSION: 0.14.0
    image: docker.io/denoland/deno:2.0.2@sha256:22d5b3a7164db3190b9591aa270f1f5e65c888ba38fa5f489532b58d57a4dd6d
    name: check-markdownlint-cli2
    volumes:
      - wp-cache_global_npm:/cache/npm

when:
  - event: pull_request
