# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - entrypoint:
      - /syft
      - scan
      - .
      - -o
      - json=$CI_COMMIT_SHA-sbom
    image: docker.io/anchore/syft:v1.14.0
    name: create-sbom
  - entrypoint:
      - /grype
      - sbom:$CI_COMMIT_SHA-sbom
    image: docker.io/anchore/grype:v0.82.0
    name: check-grype

when:
  - event: pull_request
