# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - commands:
      - corepack enable
      - pnpm config set store-dir /pnpm
      - pnpm install
      - pnpm check:prettier
    image: docker.io/library/node:23.0.0-bookworm@sha256:12eceafc86e04862a24f9cdbbdbada57fc36644bdc7e0f643e6767866cedeb1c
    name: check-prettier
    volumes:
      - woodpecker-repo-${CI_REPO_REMOTE_ID}-pnpm:/pnpm

when:
  - event: pull_request
