# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - commands:
      - checkov -d .
    image: ghcr.io/bridgecrewio/checkov:3.2.263@sha256:92a45dd78a7b1b3e2bb7d998d82ff2cde1d6cb58bd0f0853b814c42be4d10f0f
    name: check-checkov

when:
  - event: pull_request
