# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - entrypoint:
      - /grype
      - --verbose
      - dir:.
    image: docker.io/anchore/grype:v0.82.0
    name: check-grype

when:
  - event: pull_request
