# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - commands:
      - corepack enable
      - pnpm config set store-dir /pnpm
      - pnpm install
      - pnpm check:prettier
    image: docker.io/library/node:22.9.0-bookworm@sha256:69e667a79aa41ec0db50bc452a60e705ca16f35285eaf037ebe627a65a5cdf52
    name: check-prettier
    volumes:
      - woodpecker-repo-${CI_REPO_REMOTE_ID}-pnpm:/pnpm

when:
  - event: pull_request
