# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - commands:
      - apk add --no-cache yamllint
      - yamllint .
    image: docker.io/library/alpine:3.20.3
    name: check-yamllint
    volumes:
      - pnpm-cache:$CI_WORKSPACE/.pnpm-store

when:
  - event: pull_request
