# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - commands:
      - npm install -g v8r
      # Solve problem with prettier schema.
      - echo '{"customCatalog":{"schemas":[{"name":"prettier","fileMatch":["**/.prettierrc.json"],"location":"https://json.schemastore.org/prettierrc.json"}]}}' >> .v8rrc.json
      - git ls-tree --name-only -r HEAD | grep -e ".*\.json" | while read f ; do v8r "$f" ; done
      - git ls-tree --name-only -r HEAD | grep -e ".*\.yaml" | while read f ; do v8r "$f" ; done
      - git ls-tree --name-only -r HEAD | grep -e ".*\.yml" | while read f ; do v8r "$f" ; done
    image: docker.io/library/node:22.9.0-bookworm
    name: check-v8r

when:
  - event: pull_request
