# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - commands:
      - trivy repo --scanners vuln,secret,misconfig .
    image: docker.io/aquasec/trivy:0.56.1@sha256:c42bb3221509b0a9fa2291cd79a3a818b30a172ab87e9aac8a43997a5b56f293
    name: check-trivy

when:
  - event: pull_request
