# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - commands:
      - corepack enable
      - pnpm config set store-dir /pnpm
      - pnpm install
      - pnpm check:astro
    image: docker.io/library/node:23.0.0-bookworm@sha256:e643c0b70dca9704dff42e12b17f5b719dbe4f95e6392fc2dfa0c5f02ea8044d
    name: check-astro
    volumes:
      - woodpecker-repo-${CI_REPO_REMOTE_ID}-pnpm:/pnpm

when:
  - event: pull_request
