# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - commands:
      # Setup pnpm
      - corepack enable
      - pnpm config --global set store-dir /cache/pnpm

      - pnpm install
      - pnpm check:stylelint
    image: docker.io/library/node:23.0.0-bookworm@sha256:e96bb23d6ba66e6e2913f72207de972e3f36ee5c5ce77966016192e59277a73a
    name: check-stylelint
    volumes:
      - wp-cache_${CI_REPO_REMOTE_ID}_pnpm:/cache/pnpm

when:
  - event: pull_request
