# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - commands:
      - woodpecker-cli lint
    image: docker.io/woodpeckerci/woodpecker-cli:v2.7.1-alpine
    name: check-woodpecker-cli

when:
  - event: pull_request
