# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - commands:
      - npm config --global set progress false
      - npm config --global set cache /cache/npm
      - npm install -g "@commitlint/config-conventional@$COMMITLINT_CONFIG_CONVENTIONAL_VERSION" "@commitlint/cli@$COMMITLINT_CLI_VERSION"
      - export NODE_PATH=$(npm root -g)
      - commitlint -x @commitlint/config-conventional -l
    environment:
      # renovate: datasource=npm depName=@commitlint/cli versioning=npm
      COMMITLINT_CLI_VERSION: 19.5.0
      # renovate: datasource=npm depName=@commitlint/config-conventional versioning=npm
      COMMITLINT_CONFIG_CONVENTIONAL_VERSION: 19.5.0
    image: docker.io/library/node:23.0.0-bookworm@sha256:9d09fa506f5b8465c5221cbd6f980e29ae0ce9a3119e2b9bc0842e6a3f37bb59
    name: check-commitlint
    volumes:
      - wp-cache_global_npm:/cache/npm

when:
  - event: pull_request
