# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - commands:
      - corepack enable
      - pnpm install
      - pnpm exec playwright install chromium --with-deps
      - pnpm build
    image: docker.io/library/node:22.9.0-bookworm
    name: build
    volumes:
      - pnpm-cache:$CI_WORKSPACE/.pnpm-store
  - commands:
      - npx wrangler pages deploy dist
    image: docker.io/library/node:22.9.0-bookworm
    name: deploy

when:
  - branch: main
    event: push
