# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - name: build
    image: docker.io/library/node:22.9.0-bookworm
    commands:
      - corepack enable
      - pnpm install
      - pnpm exec playwright install chromium --with-deps
      - pnpm build
  - name: deploy
    image: docker.io/library/node:22.9.0-bookworm
    commands:
      - npx wrangler pages deploy dist

when:
  - event: push
    branch: main
