# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - commands:
      - deno install --allow-scripts
      - deno run build
    image: docker.io/denoland/deno:2.0.2
    name: build
    volumes:
      - wp-cache_global_deno:/deno-dir
  # Need to wait for Deno to support some NodeJS cli options.
  - commands:
      - npm config --global set progress false
      - npx "wrangler@$WRANGLER_VERSION" pages deploy ./dist --project-name $CI_REPO_NAME
    environment:
      CLOUDFLARE_API_TOKEN:
        from_secret: CLOUDFLARE_API_TOKEN
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      # renovate: datasource=npm depName=wrangler versioning=npm
      WRANGLER_VERSION: 3.83.0
    image: docker.io/library/node:23.0.0-alpine
    name: deploy

when:
  - branch: main
    event: push
