# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

steps:
  - commands:
      - bun install
      - bun run build
    image: docker.io/oven/bun:1.1.33-alpine
    name: build
    volumes:
      - wp-cache_global_bun:/root/.bun/install/cache/
  # Need to wait for Deno to support some NodeJS cli options.
  - commands:
      - bun x "wrangler@$WRANGLER_VERSION" pages deploy ./dist --project-name $CI_REPO_NAME
    environment:
      CLOUDFLARE_API_TOKEN:
        from_secret: CLOUDFLARE_API_TOKEN
      # renovate: datasource=npm depName=wrangler versioning=npm
      WRANGLER_VERSION: 3.83.0
    image: docker.io/oven/bun:1.1.33-alpine
    name: deploy
    volumes:
      - wp-cache_global_bun:/root/.bun/install/cache/

when:
  - branch: main
    event: push
