jobs:
  build:
    container: docker.io/library/node:22.9.0-bookworm@sha256:69e667a79aa41ec0db50bc452a60e705ca16f35285eaf037ebe627a65a5cdf52
    env:
      # renovate: datasource=npm depName=playwright versioning=npm
      PLAYWRIGHT_VERSION: 1.47.2
    permissions:
      id-token: write
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          cache: pnpm
      - run: pnpm dlx "playwright@$PLAYWRIGHT_VERSION" install --with-deps
      - uses: withastro/action@44cbafd43567733e3b007918c6e0711480560516 # v3.0.0
  deploy:
    container: docker.io/library/node:22.9.0-bookworm@sha256:69e667a79aa41ec0db50bc452a60e705ca16f35285eaf037ebe627a65a5cdf52
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    permissions:
      pages: write
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5

name: deploy-pages

"on":
  push:
    branches:
      - main

permissions: read-all
