jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - uses: withastro/action@44cbafd43567733e3b007918c6e0711480560516 # v3.0.0
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5

name: deploy-pages

"on":
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write
  pages: write
